---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cassandra.datastax.com.cassandra.datastax.com
  resources:
  - cassandradatacenterautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cassandra.datastax.com.cassandra.datastax.com
  resources:
  - cassandradatacenterautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - cassandra.datastax.com.cassandra.datastax.com
  resources:
  - cassandradatacenterautoscalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager-role
  namespace: cass-operator
rules:
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - cassandra.datastax.com
  resources:
  - cassandradatacenters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cassandra.datastax.com
  resources:
  - cassandradatacenters/finalizers
  verbs:
  - delete
  - update
- apiGroups:
  - cassandra.datastax.com
  resources:
  - cassandradatacenters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - control.k8ssandra.io
  resources:
  - cassandratasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - control.k8ssandra.io
  resources:
  - cassandratasks/finalizers
  verbs:
  - update
- apiGroups:
  - control.k8ssandra.io
  resources:
  - cassandratasks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - persistentvolumeclaims
  - pods
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
